# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{litmus}
  s.version = "0.2.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = [%q{Matt Fawcett}]
  s.date = %q{2011-09-29}
  s.description = %q{A wrapper to the Litmus customer API}
  s.email = %q{mail@matthewfawcett.co.uk}
  s.extra_rdoc_files = [
    "LICENSE",
    "README.md"
  ]
  s.files = [
    ".document",
    ".rspec",
    "LICENSE",
    "README.md",
    "Rakefile",
    "VERSION",
    "lib/litmus.rb",
    "lib/litmus/base.rb",
    "lib/litmus/email_test.rb",
    "lib/litmus/page_test.rb",
    "lib/litmus/result.rb",
    "lib/litmus/test.rb",
    "lib/litmus/test_version.rb",
    "litmus.gemspec",
    "spec/email_test_spec.rb",
    "spec/fixtures/all_tests.xml",
    "spec/fixtures/create_email_test.xml",
    "spec/fixtures/create_page_test.xml",
    "spec/fixtures/create_test_version.xml",
    "spec/fixtures/list_results.xml",
    "spec/fixtures/list_test_versions.xml",
    "spec/fixtures/poll_test_version.xml",
    "spec/fixtures/rename_test.xml",
    "spec/fixtures/show_result.xml",
    "spec/fixtures/show_test.xml",
    "spec/fixtures/show_test_version.xml",
    "spec/litmus_spec.rb",
    "spec/page_test_spec.rb",
    "spec/result_spec.rb",
    "spec/spec_helper.rb",
    "spec/test_spec.rb",
    "spec/test_version_spec.rb"
  ]
  s.homepage = %q{http://github.com/mattfawcett/litmus}
  s.require_paths = [%q{lib}]
  s.rubygems_version = %q{1.8.6}
  s.summary = %q{A wrapper to the Litmus customer API}

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<rspec>, [">= 1.2.9"])
      s.add_runtime_dependency(%q<httparty>, [">= 0.6.1"])
    else
      s.add_dependency(%q<rspec>, [">= 1.2.9"])
      s.add_dependency(%q<httparty>, [">= 0.6.1"])
    end
  else
    s.add_dependency(%q<rspec>, [">= 1.2.9"])
    s.add_dependency(%q<httparty>, [">= 0.6.1"])
  end
end

